import './globals.css';
import localFont from 'next/font/local'
import { Inter } from 'next/font/google';
import Header from './components/commonComponents/Header/Header';
import Footer from './components/commonComponents/Footer/Footer';
const inter = Inter({ subsets: ['latin'] })
const arial = localFont({
  src: [
    {
      path: './fonts/ArialMT.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Arial-BoldMT.woff2',
      weight: '700',
      style: 'bold',
    }
  ]
})
const furore = localFont({
  src: [
    {
      path: './fonts/Furore.woff2',
      weight: '400',
      style: 'normal',
    }
  ]
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${arial.className} ${furore.className}`}>
        <Header/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  )
}
